### PR TITLE
chore: Add codspeed

### PR DESCRIPTION
**Pull request by Stranger6667**

### CODE REVIEW

**Comment by art049** [comment]
Hi, we had a little bug on our(CodSpeed) endpoint hence one of the run didn't get reported.  It was empty so not much would have been shown here but still you should have got a message. We're rolling out a fix now so the message will appear in a few minutes. 😁 

Btw, I'm very curious about the potential complications your facing setting up the tool, don't hesitate if you think I can help!

**Comment by Stranger6667** [comment]
Hey @art049, thanks for pinging! So far the biggest obstacle is that the current project structure does not seem to be compatible with `CodSpeedHQ/action@v1` - there is no workspace in the root, so having `working-directory`-like config option would help with such a setup :)

**Comment by Stranger6667** [comment]
Though, maybe I just need to properly set a workspace instead

**Comment by art049** [comment]
> Hey @art049, thanks for pinging! So far the biggest obstacle is that the current project structure does not seem to be compatible with `CodSpeedHQ/action@v1` - there is no workspace in the root, so having `working-directory`-like config option would help with such a setup :)

Hey @Stranger6667, I hope the installation didn't give you too much troubles. Don't hesitate to let me know if you still have issues. 
By the way, I just released a [new version](https://github.com/CodSpeedHQ/action/releases/tag/v1.8.0) of the action providing the `working-directory` input so don't hesitate to use it 😄.

**Comment by Stranger6667** [comment]
Hi @art049 ! Thank you very much! :) So far so good!

**Comment by Stranger6667** [comment]
Really appreciate addressing the `working-directory` input :) Everything seems to be working as expected!

**Comment by art049** [comment]
Awesome 🎉

**Pull request merged**
