### PR TITLE
Build wheels for all the things

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
@Stranger6667 mind changing the GitHub Actions approval setting to "Users who are new to GitHub" instead of "All users"?

**Comment by Stranger6667** [comment]
@adriangb Thank you so much for working on this! I changed the settings

**Comment by adriangb** [comment]
Okay the basic structure is there and most platforms are building successfully. Some of the platforms are failing though and while I tried to keep the tox stuff working I didn't really test it. Can I kick this over to you @Stranger6667 to fix those build failures and get it across the finish line?

**Comment by Stranger6667** [comment]
@adriangb Absolutely! I will take a look at it tomorrow :) Amazing job! Thank you so much!

**Comment by Stranger6667** [comment]
A few platforms are not supported by `ring` (e.g. `ppc64` and `s390x`), so I removed them. Otherwise, everything seems to work! :) Thank you

**Comment by adriangb** [comment]
Glad to help!

**Pull request merged**
