### PR TITLE
Fix Homepage link on  pypi

### PR DESCRIPTION
**Pull request by Mogost**

### CODE REVIEW

**Comment by Stranger6667** [comment]
That link points specifically to Python bindings, so users that are coming from PyPI see the actual Python package with Python-specific README, instead of Rust sources, which I think may be confusing. What is your point of view on this? I.e. I am not against the change, but wondering what kind of improvement it might bring

**Comment by Stranger6667** [comment]
Oh, and the current link is indeed broken - I completely forgot that I moved Python bindings to the `bindings` dir

**Comment by Stranger6667** [comment]
What do you think if it could be changed to `https://github.com/Stranger6667/css-inline/tree/master/bindings/python` instead of the root dir?

**Comment by Mogost** [comment]
NP. Changed to binding dir

**Comment by Stranger6667** [comment]
Cool! Thank you for spotting this

**Pull request merged**
